[http.routers.api]
  rule = "Host(`traefik.localhost`)"
  entrypoints = ["web"]
  service = "api@internal"

[tls.options]
  [tls.options.default]
    minVersion = "VersionTLS12"
    cipherSuites = [
      "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256"
    ]
    curvePreferences = ["CurveP521", "CurveP384"]
  [tls.options.mintls13]
    minVersion = "VersionTLS13"

