[entryPoints]
  [entryPoints.web]
    address = ":80"
  [entryPoints.websecure]
    address = ":443"

[api]
  dashboard = false

[providers.docker]
  endpoint = "unix:///var/run/docker.sock"
  watch = true
  network = "web"

[providers.file]
  filename = "traefik_dynamic.toml"
